default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: active_record_development

test:
  <<: *default
  database: active_record_test

production:
  <<: *default
  database: active_record_production
  username: active_record
  password: <%= ENV["ACTIVE_RECORD_DATABASE_PASSWORD"] %>
